### ISSUE TITLE
Discussion Area

### ISSUE THREAD

**Issue by ryuujo1573** [icela/FriceEngine-CSharp#1]
Nice Frice~

**Comment by ice1000** [comment]
Functions are not all ready. Please wait for the release. 😆

**Comment by ice1000** [comment]
@ifdog 推荐你给VS装个ReSharper，或者弄个Project Rider（目前还是EAP）来写C#。

**Comment by ifdog** [comment]
其实我装了的。Rider现在是不是还没有UI编辑器，另外看见这名字就会想起一个紫色头发的盲人妹子。

**Comment by ifdog** [comment]
对，ColorResource可以加上 Rider紫。

**Comment by ice1000** [comment]
RD已经变成和IntelliJ差不多的彩色了。。。 😂

**Comment by ice1000** [comment]
我们要不要去搞个同款的Lisp IDE，叫Saber。。。图标就是SB。。。 😂

**Comment by ice1000** [comment]
RD前几天更新的build 11越来越像主流JetBrains IDE了，最主要是Integrated Version Control System，比VS不知道高到哪里去了。还有很多像markdown、CodeGlance之类的插件。

还有就是因为我个人**非常**熟悉J家IDE的各种操作。。。

**Comment by ifdog** [comment]
我以前用过Pycharm,感觉上手难度也不低。
另外VS2012的时候超好用现在用着2015确实感觉怪怪的= =！（可能是WPF的锅）。
另外还用过一款IDE叫SharpDevelop,用来开发Iron Python很好用。
如果未来Rider可以拖控件了，并且内置Resharper,并且出Community版（并且Community版有Reshaper的功能),那我一定换过去。

**Comment by ifdog** [comment]
然而好担心RD正式发布了之后会不会没有免费版了。

**Comment by ifdog** [comment]
另外：你是JB家新出一个IDE就多学一门语言么。

**Comment by ice1000** [comment]
这倒不是，我学C#一半因为Unity，一半因为我的好朋友 @iXinwei 是C#厨。
另外，按照JetBrains的风格，IntelliJ+C#插件其实就已经是半个Project Rider了。

**Comment by ice1000** [comment]
但是等你真正上手之后你就会发现这套IDE的神奇之处了，因为等你PyCharm用到老司机程度的时候，上手IntelliJ IDEA、Rider、DataGrip、CLion、Android Studio、PhpStorm、RubyMine等IDE就几乎是零门槛。

**Comment by ifdog** [comment]
所以我刚刚又下了Rider。

**Comment by ifdog** [comment]
原来Android Studio也是JB家的，我说怎么看起来这么像。

**Comment by ice1000** [comment]
肯定啊。你看Android Studio开启画面上那行”Powered by IntelliJ Platform“

**Comment by ice1000** [comment]
话说刚刚我回复你的消息被宾馆辣鸡WiFi吞了，艹。我都记不得我发了啥了。

**Comment by ice1000** [comment]
另外Android Studio不是JB家的，是Google把IntelliJ IDEA中除了Android Support相关的东西全阉割之后剩下的一个东西，再加了一大堆自己的东西（谷歌的云服务、Play Store直接build发布的支持等等等等，当然GFW所以你懂的），严格意义上不是J家的，不然JetBrains官网早就该把这个用户量远大于他们主打的IntelliJ和ReSharper的超级IDE拿出来炫耀了（话说AS即将成为VS级别的超级IDE，而且代码编辑能力完爆VS，你看看MOE，看看Cocos，虽然Cocos是辣鸡但是Intel都选了AS了）

Xcode估计要哭成狗

**Comment by ifdog** [comment]
原来如此 我说为什么这样一个Studio级别的东西  还需要推广（貌似仍然在推广
Intellij根据我写了点Kotlin的经验，确实比Eclipse好太多（话说学Java时我用的NetBeans
说到超级IDE 暂时我对Rider的期待就是，如果它能把JB家的Resharper,DotPeek等,Dot系列都集成一起再推出一个Com版，宇宙最强指日可待啊。

**Comment by ifdog** [comment]
= =以及你不是学生么，怎么又火车又宾馆的，和我高中时画风差距可太大了。

**Comment by ice1000** [comment]
嗯我现在在长沙培训OI。。。
学渣需要增强力量Daze。

**Comment by ice1000** [comment]
是的，ReSharper Ultimate就是ReSharper、ReSharper C++、dotPeek、dotMemory、dotTrace和dotCover的一个大集合。而Rider就是IntelliJ IDEA - JVM + ReSharper Ultimate。

**Comment by ice1000** [comment]
@iXinwei 你这样说句Nice却不给Star的行为是不道德的。（逃
![](http://tse2.mm.bing.net/th?id=OIP.Md8863529e9db1ca10a638911d45e0be6o0&pid=15.1)

**Comment by ice1000** [comment]
@ifdog 我看到了，就是那样！（我也要改改Kotlin版的时钟了）
