### ISSUE TITLE
为啥放在Properties里。。。

### ISSUE THREAD

**Issue by ifdog** [icela/FriceEngine-CSharp#2]
RT

**Comment by ice1000** [comment]
不知道。Rider的重构功能还不支持移动的时候改命名空间，我本来准备和Properties分开，后来看到又自动回去了，就没管。我不是很懂C#规范。给我个PR吧。

**Comment by ifdog** [comment]
T T 稍微一改就崩了

**Comment by ice1000** [comment]
既fork之，则fix之。
既fix之，则pull request之。
😂
